import './favorites/favorite-coctails';
import './favorites/favorite-ing';
import './common/dropdown-menu';
import './common/mobile-menu';
import './common/theme-toggler';
import './modals/open-close-modal';
import './common/input-validation';
import './gallery/gallery';
import './render/render';
// import './common/slider_glide';
import './common/dropdown-menu-mob';
import './favorites/search-favorites';
import './modals/team-modal';